version: '3.6'
services:
  db:
    image: mongo:3.2
    container_name: rocketchat_db
    entrypoint: mongod --smallfiles
    volumes:
    - db_data:/data/db
    - db_dump:/dump

  rocketchat:
    image: rocket.chat:0.68.5
    container_name: rocketchat
    environment:
      ROOT_URL: 'http://localhost'
    depends_on:
    - db
    ports:
      - "3000:3000"

volumes:
  db_data:
    driver: local
  db_dump:
    driver: local

networks:
  default:
    external:
      name: nginx-proxy
